default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: p_blog_development

test:
  <<: *default
  database: p_blog_test

production:
  <<: *default
  database: p_blog_production
