# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4253d1639efd912ac5f46334288c55a75857f11200ac1a57a6776dd75de87ef0035f58ec86eb443bff041c6bbff11965edda1da7540d5a9e16c246c6b0596d2

test:
  secret_key_base: c310a45feb307378bd2bc3ca19af5efa60882cf2c402a2217fdd6fa82af9d5213b3986ff366777749076cca3b863234e97228506d7ccafa9819c2da6a70a266e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
